### ISSUE TITLE
Integrate notebooks/plots with QA pipeline in ClimateMachine

### ISSUE THREAD

**Issue by bischtob** [CliMA/VizCLIMA.jl#13]
We need to auto-generate plots for a small suite of benchmark experiments that require at least some visual inspection. Typically, these experiments are run at a lower frequency in the CI/QA pipeline and in addition to numeric metrics that are helpful require diagnostics to be visualized via VizCLIMA.

**Comment by jakebolewski** [comment]
Seems like the todos here are to define the MVP (aka. the minimal vizclima project)

### Problem Definition
[] One test case to run (ideally that's fairly short so we can debug / iterate the first case)
[] The outputs to save and any pre-post processing of the results that need to happen.
[] The notebook / literate example to run and generate static output files for hosting.
[] The minimal amount of metadata to make the qa run useful (datetime / commit / what was ran at what commit, etc.)

### Problem infrastructure needed
[] create a slurm batch script to run the minimal example as a cron job
[] create some postprocessing slurm scripts to run after the qa job
[] create some vizclima scripts to generate static output of postprocessed data
[] method to copy results from cluster to google filesystem
[] method to copy filesystem data to filestore on google cloud?
[] setup webhosting for static assets on google cloud (easy), determine easy to use paths for linking results (ex. qa/datetime/<result>, or qa/sha/<result>)
[] register dns address for something easier to remember (ex. `climatemachine.dev`)

**Comment by jakebolewski** [comment]
Maybe we can add comment here about the problem definition, or add a github project to track progress as there are some incremental parts (I sketched out the rough problem decomposition above but feel free to edit / add anything).

**Comment by jakebolewski** [comment]
@akshaysridhar can you point me to the LES test case brought up in the meeting today and what the expected results / ouput should be?

**Comment by jakebolewski** [comment]
This has been implemented in: https://github.com/CliMA/ClimateMachineQA (pure python project)
Daily / weekly scheduled runs: https://buildkite.com/clima/climatemachine-qa
